name: socialrang
description: Social Rang social networking application
publish_to: "none"
version: 0.8.0+8

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  translator: ^1.0.4
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.5
  image_picker: ^1.1.2
  video_player: ^2.8.6
  share_plus: ^10.1.2
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png
