name: Build Android App Bundle and Signed APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.2'
          channel: 'stable'
          cache: true

      - name: Configure Gradle Properties
        run: |
          echo "org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

      - name: Generate Keystore and Setup Properties
        run: |
          # गिटहब सर्वर पर बिना रुके अपने आप कीस्टोर फाइल बना देगा
          keytool -genkey -v -keystore android/app/upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -storepass android -keypass android -dname "CN=Virender Bhasker, OU=Development, O=SocialRang, L=Ludhiana, ST=Punjab, C=IN"
          
          # android/key.properties फाइल में एंट्री कर देगा
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=android" >> android/key.properties
          echo "keyPassword=android" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate App Icon
        run: dart run flutter_launcher_icons

      - name: Build Release App Bundle and APK
        run: |
          flutter build appbundle --release --no-pub --android-skip-build-dependency-validation
          flutter build apk --release --no-pub --android-skip-build-dependency-validation --target-platform android-arm,android-arm64,android-x64

      - name: Upload App Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
