name: Build Android App Bundle and Signed APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.2'
          channel: 'stable'
          cache: true

      - name: Configure Gradle Properties
        run: |
          echo "org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

      - name: Setup Keystore from Secrets
        env:
          STORE_PASSWORD: ${{ secrets.MY_UPLOAD_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.MY_UPLOAD_KEY_PASSWORD }}
        run: |
          # गिटहब सीक्रेट्स का उपयोग करके परमानेंट कीस्टोर जनरेट करना
          keytool -genkeypair -v -keystore android/app/upload-keystore.jks -storepass "$STORE_PASSWORD" -alias upload -keypass "$KEY_PASSWORD" -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Virender Bhasker, OU=Development, O=SocialRang, L=Ludhiana, ST=Punjab, C=IN" || true
          
          # android/key.properties फाइल तैयार करना
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=$STORE_PASSWORD" >> android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate App Icon
        run: dart run flutter_launcher_icons

      - name: Build Debug APK
        run: |
          flutter build apk --debug --no-pub --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
